/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <string.h>
#include <time.h>
#include "gestionHamburguesas.h"
int idClientes=1;
proxNodoHamburguesa cabeza = NULL, sigHamburguesa;
proxNodoHamburguesa nuevaHamburguesa;
char varCapcha[10];

int *
getidentificador_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("\n ********Generando Nuevo Codigo De Usuario*********");	
	result=idClientes;
	idClientes++;
	return &result;
}

nodo_datos_empresa *
consultardatosempresa_1_svc(void *argp, struct svc_req *rqstp)
{
	static nodo_datos_empresa  result;
	printf("\n ********Ejecutando Consulta Datos Empresa*********");
	FILE *archivo;
	char lineaLeida[100];
	archivo = fopen("datosEmpresa.txt","r");
	if (archivo == NULL)
	{
		printf("Erro al abrir el archivo");
	} 		
	else
	{
			fgets(lineaLeida,100,archivo);
			strcpy(result.nombre,lineaLeida);
			fgets(lineaLeida,100,archivo);
			result.nit = atoi(lineaLeida);				
	}
	fclose(archivo);
	printf("	 Nombre Empresa: %s \n",result.nombre);
	printf("	 Nit Empresa: %i \n",result.nit);

	return &result;
}

nodo_costos_hamburguesa obtenerCostos(){

	nodo_costos_hamburguesa  result;
	FILE *archivo;
	char lineaLeida[100];
	archivo = fopen("costoshamburguesa.txt","r");
	//printf("\n Ejecutando Consulta de Precios. \n");
	if (archivo == NULL)
	{
		printf("Erro al abrir el archivo");
	} 		
	else
	{
			fgets(lineaLeida,100,archivo);


			result.costoHamburguesaPequenia = atof(lineaLeida);
			fgets(lineaLeida,100,archivo);
			result.costoHamburguesaMediana = atof(lineaLeida);
			fgets(lineaLeida,100,archivo);
			result.costoHamburguesaGrande = atof(lineaLeida);
			fgets(lineaLeida,100,archivo);
			result.costoIngredientesExtra = atof(lineaLeida);
	
	}
	fclose(archivo);
	/*printf("\n Hamburguesa Pequeña: %f \n",result.costoHamburguesaPequenia);
	printf("\n Hamburguesa Mediana: %f \n",result.costoHamburguesaMediana);
	printf("\n Hamburguesa Grande: %f \n",result.costoHamburguesaGrande);
	printf("\n Ingredientes Extra: %f \n",result.costoIngredientesExtra);*/

	return result;
}

nodo_costos_hamburguesa *
consultarcostoshamburguesa_1_svc(void *argp, struct svc_req *rqstp)
{
	static nodo_costos_hamburguesa  result;	
	printf("\n ********Ejecutando Consulta de Precios*********");
	result =obtenerCostos();
	return &result;	
}

float calcularCostoHamburguesa(char *tipo, int cantIngredientes){
	float result = 0;
	float valor=0;
	//printf("\n CALCULANDO COSTO: ");
	//printf("\n Tipo recibido: %s \n",tipo);
	nodo_costos_hamburguesa costos = obtenerCostos();
	if (strcmp(tipo,"Pequenia")==0){
		valor = costos.costoHamburguesaPequenia;		
	}
	if (strcmp(tipo,"Mediana")==0){
		valor = costos.costoHamburguesaMediana;		
	}
	if (strcmp(tipo,"Grande")==0){
		valor = costos.costoHamburguesaGrande;		
	}
	//printf("\n Ingredientes Extra: %f \n",costos.costoIngredientesExtra);
	float valExtra = costos.costoIngredientesExtra*cantIngredientes;
	result = valor+valExtra;
	return result;
}

bool_t hamburguesaRepetida(char parNombre[30]){

	bool_t respuesta = FALSE;
	proxNodoHamburguesa hamburguesaActual;
	hamburguesaActual = cabeza;
	while (hamburguesaActual!=NULL){
		if (strcmp(hamburguesaActual->nombre,parNombre)==0){
			respuesta = TRUE;
			break;
		}
		hamburguesaActual=hamburguesaActual->nodoSiguiente;
	}
	return respuesta;	
}

bool_t *
comprarhamburguesasistema_1_svc(nodo_hamburguesa_factura *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	result = FALSE;
	if (hamburguesaRepetida((*argp).nombre)== FALSE){

		printf("\n *****Ejecutando Compra de Hamburguesas***** \n");
		/*printf("	Id Cliente: %i \n", (*argp).idCliente);
		printf("	Nombre: %s \n", (*argp).nombre);
		printf("	Cantidad Ingredientes: %d \n", (*argp).cantidadIngredientesExtra);
		printf("	Tipo: %s \n", (*argp).tipo);*/

		nuevaHamburguesa = (proxNodoHamburguesa) malloc (sizeof (nodo_hamburguesa_factura) );
	
		strcpy(nuevaHamburguesa->nombre,(*argp).nombre);
		nuevaHamburguesa->cantidadIngredientesExtra = (*argp).cantidadIngredientesExtra;
		nuevaHamburguesa->idCliente=(*argp).idCliente;
		strcpy(nuevaHamburguesa->tipo,(*argp).tipo);

		nuevaHamburguesa->costo = calcularCostoHamburguesa(nuevaHamburguesa->tipo,nuevaHamburguesa->cantidadIngredientesExtra);


		if (cabeza==NULL)
		{
			cabeza = nuevaHamburguesa;
			sigHamburguesa = cabeza;
		}
		else
		{
			sigHamburguesa->nodoSiguiente = nuevaHamburguesa;
			sigHamburguesa=nuevaHamburguesa;
		}
		sigHamburguesa->nodoSiguiente=NULL;

		result=TRUE;

	}

	return &result;
}

nodo_hamburguesa *
obtenerhamburguesa_1_svc(char **argp, struct svc_req *rqstp)
{
	static nodo_hamburguesa  result;
	//printf("\nNombre de hamburguesa recibido:%s ", *argp);
	proxNodoHamburguesa hamburguesaActual;
	hamburguesaActual = cabeza;
	while (hamburguesaActual!=NULL){
		if (strcmp(hamburguesaActual->nombre,*argp)==0){

			strcpy(result.nombre,hamburguesaActual->nombre);
			result.cantidadIngredientesExtra = hamburguesaActual->cantidadIngredientesExtra;
			strcpy(result.tipo,hamburguesaActual->tipo);
			result.idCliente = hamburguesaActual->idCliente;
			break;
		}
		hamburguesaActual=hamburguesaActual->nodoSiguiente;
	}

	return &result;
}

bool_t *
modificarcompra_1_svc(nodo_datos_hamburguesa_modificada *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	printf("\n ********Ejecutando Modificacion Hamburguesa*********");
	proxNodoHamburguesa hamburguesaActual;
	hamburguesaActual=cabeza;
	result = FALSE;
	while (hamburguesaActual!=NULL){
		if (strcmp(hamburguesaActual->nombre,(*argp).nombreAntiguo)==0){
			strcpy(hamburguesaActual->nombre,(*argp).varHamburguesa.nombre);
			hamburguesaActual->cantidadIngredientesExtra = (*argp).varHamburguesa.cantidadIngredientesExtra;
			strcpy(hamburguesaActual->tipo,(*argp).varHamburguesa.tipo);
			hamburguesaActual->costo = calcularCostoHamburguesa(hamburguesaActual->tipo,hamburguesaActual->cantidadIngredientesExtra);
			result = TRUE;	
			break;			
		}
		else {
			hamburguesaActual=hamburguesaActual->nodoSiguiente;
		}	
	}

	return &result;
}

bool_t *
eliminarahamburguesa_1_svc(char **argp, struct svc_req *rqstp)
{
	static bool_t  result;
	printf("\n ********Ejecutando Eliminacion Hamburguesa*********");
	proxNodoHamburguesa hamburguesaActual;
	proxNodoHamburguesa nodoAnterior;
	//Si el resultado es falso es porque seguramente no encontró la hamburguesa (?)
	result=FALSE;
	if (cabeza!=NULL){
		
		if (strcmp(cabeza->nombre,*argp)==0){
			nodoAnterior=cabeza;
			cabeza = nodoAnterior->nodoSiguiente;
			nodoAnterior=NULL;
			result=TRUE;
		}
		else {
			hamburguesaActual=cabeza;
			while (hamburguesaActual->nodoSiguiente != NULL){
				if (strcmp(hamburguesaActual->nodoSiguiente->nombre,*argp)==0){
				
					if (hamburguesaActual->nodoSiguiente->nodoSiguiente == NULL){
						sigHamburguesa=hamburguesaActual;
						hamburguesaActual=NULL;
					}
					else{
						hamburguesaActual->nodoSiguiente = hamburguesaActual->nodoSiguiente->nodoSiguiente;
					}
				
					result = TRUE;	
					break;			
				}
				else {
					hamburguesaActual=hamburguesaActual->nodoSiguiente;
				}	
			}
		
		}
		printf("\Eliminacion completada.");
	}
	return &result;
}


proxNodoHamburguesa listarHamburguesasCliente(int parId){

	//printf("\n Id Recibido: %i \n",parId);

	proxNodoHamburguesa nuevaCabeza = NULL, varSigHamburguesa;

	proxNodoHamburguesa hamburguesaNueva;
	proxNodoHamburguesa hamburguesaActual;
	hamburguesaActual=cabeza;
	int cont=0;

	while (hamburguesaActual!=NULL){
		if (hamburguesaActual->idCliente==parId){

			hamburguesaNueva = (proxNodoHamburguesa) malloc (sizeof (nodo_hamburguesa_factura) );	
			strcpy(hamburguesaNueva->nombre,hamburguesaActual->nombre);
			hamburguesaNueva->cantidadIngredientesExtra = hamburguesaActual->cantidadIngredientesExtra;
			strcpy(hamburguesaNueva->tipo,hamburguesaActual->tipo);
			hamburguesaNueva->costo = hamburguesaActual->costo;
			hamburguesaNueva->idCliente = hamburguesaActual->idCliente;
			hamburguesaNueva->nodoSiguiente=NULL;
			if (nuevaCabeza==NULL)
			{
				nuevaCabeza = hamburguesaNueva;
				varSigHamburguesa = nuevaCabeza;
			}
			else
			{
				varSigHamburguesa->nodoSiguiente = hamburguesaNueva;
				varSigHamburguesa=hamburguesaNueva;
			}
			sigHamburguesa->nodoSiguiente=NULL;
			cont++;
		
		}
		hamburguesaActual=hamburguesaActual->nodoSiguiente;		
	}
	//printf("Numero de hamburguesas listadas: %i",cont);
	return nuevaCabeza;
	
}



nodo_factura *
mostrarfactura_1_svc(int *argp, struct svc_req *rqstp)
{
	static nodo_factura  result;
	printf("\n ********Ejecutando Generacion de Factura*********");
	int numGrandes=0, numMedianas=0, numPequenias=0;
	float costoSinIva=0,iva=0,costoTotal=0;
	result.listaHamburguesas = listarHamburguesasCliente(*argp);
	proxNodoHamburguesa hamburguesaActual;
	hamburguesaActual = result.listaHamburguesas;
	while (hamburguesaActual!=NULL){
		if (strcmp(hamburguesaActual->tipo,"Pequenia")==0){
			numPequenias++;
		}
		if (strcmp(hamburguesaActual->tipo,"Mediana")==0){
			numMedianas++;
		}
		if (strcmp(hamburguesaActual->tipo,"Grande")==0){
			numGrandes++;
		}
		costoSinIva+=hamburguesaActual->costo;	
		hamburguesaActual=hamburguesaActual->nodoSiguiente;	
	}
	result.cantidadHamburguesasPequenias=numPequenias;
	result.cantidadHamburguesasMedianas=numMedianas;
	result.cantidadHamburguesasGrandes=numGrandes;
	int cantHamburguesas = numGrandes+numMedianas+numPequenias;
	if (cantHamburguesas >=1 && cantHamburguesas <=3){
		iva=costoSinIva*0.05;
	}
	else if (cantHamburguesas >=4 && cantHamburguesas <=7){
		iva=costoSinIva*0.08;
	}
	else if (cantHamburguesas >=8 && costoSinIva == 120000){
		iva=costoSinIva*0.18;
	}
	else if (cantHamburguesas >=8 ){
		iva=costoSinIva*0.15;
	}

	result.costoSinIva=costoSinIva;
	result.costoIva = iva;
	result.costo_total = costoSinIva+iva;
	strcpy(result.id_factura,"factura_");
	char varNum[4]; sprintf(varNum,"%i",*argp);
	strcat(result.id_factura,varNum);
	result.idCliente = *argp;
	result.nodoFacturaSiguiente=NULL;

	return &result;
}

bool_t *
pagarfactura_1_svc(nodo_pago *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	result = TRUE;
	printf("\n ********Ejecutando Pago de Factura*********");
	//Creacion de la carpeta Facturas
	DIR * dir;
	dir = opendir("Facturas");
	if(dir == NULL){
		int n = mkdir("Facturas", 0777);
		if (n == -1){
			printf("No se creo el directorio!");
			exit(EXIT_FAILURE);
			result = FALSE;
		}
		closedir(dir);
		
	}
	
	//Creacion del archivo pagos
	FILE *archivoPagos;
	archivoPagos = fopen("Facturas/PagosFacturas.txt","a");
	char montoPago[30];
	sprintf(montoPago,"%f",(*argp).varFactura.costo_total);
	fputs(montoPago,archivoPagos); fputs("\n",archivoPagos);
	fclose(archivoPagos);

	//Creando el archivo para la factura en particular

	FILE *archivoFactura;
	char nombreArchivo[30];
	strcpy(nombreArchivo,(*argp).varFactura.id_factura); strcat(nombreArchivo,".txt");
	char ruta[50]="Facturas/";
	strcat(ruta,nombreArchivo);
	archivoFactura = fopen(ruta,"w");

	fputs("Metodo de Pago: ",archivoFactura); fputs((*argp).varTipoPago,archivoFactura);fputs("\n",archivoFactura);

	fputs("Costo Total: ",archivoFactura); fputs(montoPago,archivoFactura);fputs("\n",archivoFactura);

	char costoIva[30];
	sprintf(costoIva,"%f",(*argp).varFactura.costoIva);
	fputs("Costo Iva: ",archivoFactura); fputs(costoIva,archivoFactura);fputs("\n",archivoFactura);

	char costoSinIva[30];
	sprintf(costoSinIva,"%f",(*argp).varFactura.costoSinIva);
	fputs("Costo Sin Iva: ",archivoFactura); fputs(costoSinIva,archivoFactura);fputs("\n",archivoFactura);

	char hamburguesasPequenias[30];
	sprintf(hamburguesasPequenias,"%i",(*argp).varFactura.cantidadHamburguesasPequenias);
	fputs("Num Hamburuguesas Pequeñas: ",archivoFactura); fputs(hamburguesasPequenias,archivoFactura);fputs("\n",archivoFactura);

	char hamburguesasMedianas[30];	
	sprintf(hamburguesasMedianas,"%i",(*argp).varFactura.cantidadHamburguesasMedianas);
	fputs("Num Hamburuguesas Medianas: ",archivoFactura); fputs(hamburguesasMedianas,archivoFactura);fputs("\n",archivoFactura);

	char hamburguesasGrandes[30];	
	sprintf(hamburguesasGrandes,"%i",(*argp).varFactura.cantidadHamburguesasGrandes);
	fputs("Num Hamburuguesas Grandes: ",archivoFactura); fputs(hamburguesasGrandes,archivoFactura);fputs("\n",archivoFactura);

	proxNodoHamburguesa * hamburguesaActual;


	fputs("Lista Hamburguesas:",archivoFactura); fputs("\n",archivoFactura);
	hamburguesaActual = &(*argp).varFactura.listaHamburguesas;
	while (*(hamburguesaActual)!=NULL){
		
		fputs("-----------------------------------------",archivoFactura); fputs("\n",archivoFactura);
		fputs("	Nombre: ",archivoFactura);fputs((*hamburguesaActual)->nombre,archivoFactura); fputs("\n",archivoFactura);
		fputs("	Tipo: ",archivoFactura);fputs((*hamburguesaActual)->tipo,archivoFactura); fputs("\n",archivoFactura);
	
		char cantIngrediente[10];
		sprintf(cantIngrediente,"%i",(*hamburguesaActual)->cantidadIngredientesExtra);
		fputs("	Ingredientes Extra: ",archivoFactura);fputs(cantIngrediente,archivoFactura); fputs("\n",archivoFactura);

		char costoHam[10];
		sprintf(costoHam,"%f",(*hamburguesaActual)->costo);
		fputs("	Costo: ",archivoFactura);fputs(costoHam,archivoFactura); fputs("\n",archivoFactura);
		fputs("-----------------------------------------",archivoFactura); fputs("\n",archivoFactura);

		(*hamburguesaActual)=(*hamburguesaActual)->nodoSiguiente;	
	}

	fclose(archivoFactura);


	return &result;
}

proxNodoHamburguesa *
listarhamburguesassistema_1_svc(int *argp, struct svc_req *rqstp)
{
	static proxNodoHamburguesa  result;
	printf("\n ********Ejecutando Lista De Hamburguesas Compradas*********");
	result = listarHamburguesasCliente(*argp);

	return &result;
}



