/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionHamburguesas.h"
int codigoCliente=0;
int desplegarMenu(){

	printf("\n=================  MENU  =================");
	printf("\n	1. Ver Datos Empresa	");
	printf("\n	2. Comprar Hamburguesa	");
	printf("\n	4. Eliminar hamburguesa	");
	printf("\n	5. Listar Hamburguesass pedidas");
	printf("\n	0. Salir			");
	printf("\n=================        =================");
	printf("\nDigite opcion: ");
}
nodo_hamburguesa_factura crearHamburguesa(){
	nodo_hamburguesa_factura objHamburguesa;
	printf("\n Digite el nombre de la hamburguesa: ");
	scanf("%s", objHamburguesa.nombre);
	printf("\n Digite la cantidad de ingredientes extra: ");
	scanf("%d", &objHamburguesa.cantidadIngredientesExtra);
	fflush(stdin);
	int varOpcion;
	do{
		printf("\n Seleccione el tipo de hamburguesa 1 para pequeÃ±a, 2 para mediana, 3 para grande: ");
		scanf("%i", &varOpcion);
		switch(varOpcion)
		{
			case 1: strcpy(objHamburguesa.tipo,"Pequenia"); break; 
			case 2: strcpy(objHamburguesa.tipo,"Mediana"); break;
			case 3: strcpy(objHamburguesa.tipo,"Grande"); break;
		}
	} while (varOpcion<1 || varOpcion>3);	
	printf("\n Si se crea la amburguesa antes de mandarla ");
	objHamburguesa.nodoSiguiente=NULL;
	objHamburguesa.idCliente=codigoCliente;
	return objHamburguesa;	
}

void
gestion_hamburguesa_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char *getidentificador_1_arg;
	nodo_datos_empresa  *result_2;
	char *consultardatosempresa_1_arg;
	nodo_costos_hamburguesa  *result_3;
	char *consultarcostoshamburguesa_1_arg;
	bool_t  *result_4;
	nodo_hamburguesa_factura  comprarhamburguesasistema_1_arg;
	nodo_hamburguesa  *result_5;
	char * obtenerhamburguesa_1_arg;
	bool_t  *result_6;
	nodo_datos_hamburguesa_modificada  modificarcompra_1_arg;
	bool_t  *result_7;
	char * eliminarahamburguesa_1_arg;
	nodo_factura  *result_8;
	int  mostrarfactura_1_arg;
	bool_t  *result_9;
	nodo_pago  pagarfactura_1_arg;
	proxNodoHamburguesa  *result_10;
	int  listarhamburguesassistema_1_arg;
	bool_t  *result_11;
	char * verificar_capcha_1_arg;
	char * *result_12;
	char *recibir_capcha_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, gestion_hamburguesa, gestion_hamburguesa_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	result_1 = getidentificador_1((void*)&getidentificador_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	codigoCliente = *result_1;
	int varOpcion;

	do{
		desplegarMenu();
		scanf("%i",&varOpcion);
		switch(varOpcion){
			case 2: /*
				result_12 = recibir_capcha_1((void*)&recibir_capcha_1_arg, clnt);
				if (result_12 == (char **) NULL) {
					clnt_perror (clnt, "call failed");
				}
				printf("El captcha generado por el servidor es: %s", *result_12);
				printf("  Ingrese el captcha: ");
				verificar_capcha_1_arg = (char*)malloc(sizeof(char)*10);
				scanf("%s",verificar_capcha_1_arg);

				result_11 = verificar_capcha_1(&verificar_capcha_1_arg, clnt);
				if (result_11 == (bool_t *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				if (*result_11 == FALSE){
					printf(" El captcha No Coincide!\n");
				}
				else if (*result_11 == TRUE){ */
					printf("Capcha Correcto\n");
					comprarhamburguesasistema_1_arg = crearHamburguesa();
					printf("Hamburguesa creada y lista para madnar\n");
					result_4 = comprarhamburguesasistema_1(&comprarhamburguesasistema_1_arg, clnt);
					if (result_4 == (bool_t *) NULL) {
						clnt_perror (clnt, "call failed");
					}
					else if (*result_4 == TRUE){
						printf("Hamburguesa Registrada exitosamente!");
					}
					else if (*result_4 == FALSE){
						printf("Hamburguesa No Resistrada!");
					}
				/*}*/
				break;
			case 4:
				//Meter todos estos bloques dentro de una funcion que reciba el parametro clnt
				
				printf("\n  Ingrese Nombre hamburguesa:\n");
				scanf("%s",eliminarahamburguesa_1_arg);

				result_7 = eliminarahamburguesa_1(&eliminarahamburguesa_1_arg, clnt);
				if (result_7 == (bool_t *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				if (*result_7 == TRUE){
					printf("\nHaburguesa eliminada correctamente\n");
				}
				if (*result_7 == FALSE){
					printf("\nHamburguesa No Se Puede Registrar\n");
				}
				break;
			case 5:
				

				listarhamburguesassistema_1_arg=codigoCliente;
				printf("\n Contenido argumento listar: %i \n",listarhamburguesassistema_1_arg);
				result_10 = listarhamburguesassistema_1(&listarhamburguesassistema_1_arg, clnt);
				int i=0;
				if (result_10 == (proxNodoHamburguesa *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else {
				printf("\n Mostrando listado de hamburguesas \n");
					while((*result_10)!=NULL){
						printf("\n      Hamburguesa %i: ",i+1);
						printf("\n	Nombre de la hamburguesa: %s ",(*result_10)->nombre);
						printf("\n	Cantidad de Ingredientes de la hamburguesa: %i \n",(*result_10)->cantidadIngredientesExtra);
						printf("	Tipo de la hamburguesa: %s \n",(*result_10)->tipo);
						(*result_10)=(*result_10)->nodoSiguiente;
						i++;
					}	
					if (i==0){
						printf("	Aun no existen hamburguesas registradas. \n");
					}
				}
				break;
			
		}

	} while(varOpcion!=0);

	
	
	result_2 = consultardatosempresa_1((void*)&consultardatosempresa_1_arg, clnt);
	if (result_2 == (nodo_datos_empresa *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = consultarcostoshamburguesa_1((void*)&consultarcostoshamburguesa_1_arg, clnt);
	if (result_3 == (nodo_costos_hamburguesa *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = comprarhamburguesasistema_1(&comprarhamburguesasistema_1_arg, clnt);
	if (result_4 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = obtenerhamburguesa_1(&obtenerhamburguesa_1_arg, clnt);
	if (result_5 == (nodo_hamburguesa *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = modificarcompra_1(&modificarcompra_1_arg, clnt);
	if (result_6 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = eliminarahamburguesa_1(&eliminarahamburguesa_1_arg, clnt);
	if (result_7 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = mostrarfactura_1(&mostrarfactura_1_arg, clnt);
	if (result_8 == (nodo_factura *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = pagarfactura_1(&pagarfactura_1_arg, clnt);
	if (result_9 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_10 = listarhamburguesassistema_1(&listarhamburguesassistema_1_arg, clnt);
	if (result_10 == (proxNodoHamburguesa *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	result_12 = recibir_capcha_1((void*)&recibir_capcha_1_arg, clnt);
	if (result_12 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_hamburguesa_1 (host);
exit (0);
}
