/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GESTIONHAMBURGUESAS_H_RPCGEN
#define _GESTIONHAMBURGUESAS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 30
#define MAXTIPO 20

typedef struct nodo_hamburguesa *proxNodoHamburguesa;

struct nodo_hamburguesa {
	char nombre[MAXNOM];
	int cantidadIngredientesExtra;
	char tipo[MAXTIPO];
	proxNodoHamburguesa nodoSiguiente;
};
typedef struct nodo_hamburguesa nodo_hamburguesa;

struct nodo_costos_hamburguesa {
	float costoHamburguesaPequenia;
	float costoHamburguesaMediana;
	float costoHamburguesaGrande;
	float costoIngredientesExtra;
};
typedef struct nodo_costos_hamburguesa nodo_costos_hamburguesa;

#define gestion_hamburguesa 0x20000001
#define gestion_hamburguesa_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define consultarCostosHamburguesa 1
extern  nodo_costos_hamburguesa * consultarcostoshamburguesa_1(void *, CLIENT *);
extern  nodo_costos_hamburguesa * consultarcostoshamburguesa_1_svc(void *, struct svc_req *);
#define registrarHamburguesaSistema 2
extern  bool_t * registrarhamburguesasistema_1(nodo_hamburguesa *, CLIENT *);
extern  bool_t * registrarhamburguesasistema_1_svc(nodo_hamburguesa *, struct svc_req *);
#define listarHamburguesasSistema 3
extern  proxNodoHamburguesa * listarhamburguesassistema_1(void *, CLIENT *);
extern  proxNodoHamburguesa * listarhamburguesassistema_1_svc(void *, struct svc_req *);
extern int gestion_hamburguesa_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define consultarCostosHamburguesa 1
extern  nodo_costos_hamburguesa * consultarcostoshamburguesa_1();
extern  nodo_costos_hamburguesa * consultarcostoshamburguesa_1_svc();
#define registrarHamburguesaSistema 2
extern  bool_t * registrarhamburguesasistema_1();
extern  bool_t * registrarhamburguesasistema_1_svc();
#define listarHamburguesasSistema 3
extern  proxNodoHamburguesa * listarhamburguesassistema_1();
extern  proxNodoHamburguesa * listarhamburguesassistema_1_svc();
extern int gestion_hamburguesa_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_proxNodoHamburguesa (XDR *, proxNodoHamburguesa*);
extern  bool_t xdr_nodo_hamburguesa (XDR *, nodo_hamburguesa*);
extern  bool_t xdr_nodo_costos_hamburguesa (XDR *, nodo_costos_hamburguesa*);

#else /* K&R C */
extern bool_t xdr_proxNodoHamburguesa ();
extern bool_t xdr_nodo_hamburguesa ();
extern bool_t xdr_nodo_costos_hamburguesa ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GESTIONHAMBURGUESAS_H_RPCGEN */
