/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionFacturas.h"
void menu(){
	printf("\n================MENU================");
	printf("\n	1. Mostrar cantidad de facturas");
	printf("\n	2. Mostrar precio total de las facturas");
	printf("\n	3. Salir \n");	
}

void
gestion_facturas_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char *consultarnumfacturas_1_arg;
	float  *result_2;
	char *consultarcostototalcompras_1_arg;
	int varOpcion;
#ifndef	DEBUG
	clnt = clnt_create (host, gestion_facturas, gestion_hamburguesa_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	do {
		
		menu();
		printf("\n  Ingrese una Opcion: ");	
		scanf("%i",&varOpcion);
		switch(varOpcion)
		{
			case 1:
				result_1 = consultarnumfacturas_1((void*)&consultarnumfacturas_1_arg, clnt);
				if (result_1 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else{
					printf("\nCantidad de ventas:%d\n",*result_1);
				}
			break;	
			case 2:
				result_2 = consultarcostototalcompras_1((void*)&consultarcostototalcompras_1_arg, clnt);
				if (result_2 == (float *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else{
					printf("\nValor total de las ventas:%f\n",*result_2);	
				}
			break;
		}
	}while(varOpcion != 3);
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_facturas_1 (host);
exit (0);
}
