/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gestionHamburguesas.h"

bool_t
xdr_proxNodoHamburguesa (XDR *xdrs, proxNodoHamburguesa *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct nodo_hamburguesa), (xdrproc_t) xdr_nodo_hamburguesa))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_hamburguesa (XDR *xdrs, nodo_hamburguesa *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nombre, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantidadIngredientesExtra))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->tipo, MAXTIPO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_proxNodoHamburguesa (xdrs, &objp->nodoSiguiente))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_costos_hamburguesa (XDR *xdrs, nodo_costos_hamburguesa *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->costoHamburguesaPequenia))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->costoHamburguesaMediana))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->costoHamburguesaGrande))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->costoIngredientesExtra))
		 return FALSE;
	return TRUE;
}
