/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gestionHamburguesas.h"

bool_t
xdr_proxNodoHamburguesa (XDR *xdrs, proxNodoHamburguesa *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct nodo_hamburguesa_factura), (xdrproc_t) xdr_nodo_hamburguesa_factura))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_hamburguesa (XDR *xdrs, nodo_hamburguesa *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nombre, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantidadIngredientesExtra))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->tipo, MAXTIPO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->idCliente))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_hamburguesa_factura (XDR *xdrs, nodo_hamburguesa_factura *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nombre, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantidadIngredientesExtra))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->tipo, MAXTIPO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->idCliente))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->costo))
		 return FALSE;
	 if (!xdr_proxNodoHamburguesa (xdrs, &objp->nodoSiguiente))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_datos_empresa (XDR *xdrs, nodo_datos_empresa *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nombre, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nit))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_costos_hamburguesa (XDR *xdrs, nodo_costos_hamburguesa *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->costoHamburguesaPequenia))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->costoHamburguesaMediana))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->costoHamburguesaGrande))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->costoIngredientesExtra))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_factura (XDR *xdrs, nodo_factura *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->id_factura, MAXNOM,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_proxNodoHamburguesa (xdrs, &objp->listaHamburguesas))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->cantidadHamburguesasPequenias))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cantidadHamburguesasMedianas))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cantidadHamburguesasGrandes))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->cantidadHamburguesasPequenias);
		IXDR_PUT_LONG(buf, objp->cantidadHamburguesasMedianas);
		IXDR_PUT_LONG(buf, objp->cantidadHamburguesasGrandes);
		}
		 if (!xdr_float (xdrs, &objp->costoSinIva))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->costoIva))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->costo_total))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->id_factura, MAXNOM,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_proxNodoHamburguesa (xdrs, &objp->listaHamburguesas))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->cantidadHamburguesasPequenias))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cantidadHamburguesasMedianas))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cantidadHamburguesasGrandes))
				 return FALSE;

		} else {
		objp->cantidadHamburguesasPequenias = IXDR_GET_LONG(buf);
		objp->cantidadHamburguesasMedianas = IXDR_GET_LONG(buf);
		objp->cantidadHamburguesasGrandes = IXDR_GET_LONG(buf);
		}
		 if (!xdr_float (xdrs, &objp->costoSinIva))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->costoIva))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->costo_total))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->id_factura, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_proxNodoHamburguesa (xdrs, &objp->listaHamburguesas))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantidadHamburguesasPequenias))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantidadHamburguesasMedianas))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantidadHamburguesasGrandes))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->costoSinIva))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->costoIva))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->costo_total))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_datos_hamburguesa_modificada (XDR *xdrs, nodo_datos_hamburguesa_modificada *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_nodo_hamburguesa (xdrs, &objp->varHamburguesa))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombreAntiguo, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
