/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionHamburguesas.h"
int codigoCliente=0;
int flagSalida=0;
int desplegarMenu(){

	printf("\n=================  MENU  =================");
	printf("\n	1. Ver Datos De La Empresa");
	printf("\n	2. Comprar Hamburguesa");
	printf("\n	3. Modificar Compra De Hamburguesa");
	printf("\n	4. Eliminar Hamburguesa	Del Pedido ");
	printf("\n	5. Listar Hamburguesass Pedidas");
	printf("\n	6. Mostrar Facturas y Pagar Pedido");
	printf("\n	0. Salir			");
	printf("\n=================        =================");
	printf("\nDigite opcion: ");
}
void desplegarMenuPagos(){
	printf("\n========  SELECCIONE METODO DE PAGO  =========");
	printf("\n	1. Efectivo	");
	printf("\n	2. Targeta De Credito	");
	printf("\n	3. Pago En Linea	");
	printf("\n	4. Retornar al menu principal");
	printf("\n===================        ===================");
	printf("\nDigite opcion: ");

}
nodo_hamburguesa_factura crearHamburguesa(){
	nodo_hamburguesa_factura objHamburguesa;
	printf("\n Digite el nombre de la hamburguesa: ");
	scanf("%s", objHamburguesa.nombre);
	printf("\n Digite la cantidad de ingredientes extra: ");
	scanf("%d", &objHamburguesa.cantidadIngredientesExtra);
	fflush(stdin);
	int varOpcion;
	do{
		printf("\n Seleccione el tipo de hamburguesa: 1 Para PEQUENIA, 2 para MEDIANA, 3 para GRANDE: ");
		scanf("%i", &varOpcion);
		switch(varOpcion)
		{
			case 1: strcpy(objHamburguesa.tipo,"Pequenia"); break; 
			case 2: strcpy(objHamburguesa.tipo,"Mediana"); break;
			case 3: strcpy(objHamburguesa.tipo,"Grande"); break;
		}
	} while (varOpcion<1 || varOpcion>3);	

	objHamburguesa.nodoSiguiente=NULL;
	objHamburguesa.idCliente=codigoCliente;
	return objHamburguesa;	
}

void compraHamburguesa(CLIENT *clnt){
	bool_t  *result_4;
	nodo_hamburguesa_factura  comprarhamburguesasistema_1_arg;
	comprarhamburguesasistema_1_arg = crearHamburguesa();
	result_4 = comprarhamburguesasistema_1(&comprarhamburguesasistema_1_arg, clnt);
	if (result_4 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else if (*result_4 == TRUE){
		printf("Hamburguesa Registrada exitosamente!");
	}
	else if (*result_4 == FALSE){
		printf("Hamburguesa No Resistrada!");
	}	
}

void eliminarHamburguesa(CLIENT *clnt){
	bool_t  *result_7;
	char * eliminarahamburguesa_1_arg;
	printf("\n  Ingrese Nombre hamburguesa: ");
	eliminarahamburguesa_1_arg=(char*)malloc(sizeof(char)*30);
	scanf("%s",eliminarahamburguesa_1_arg);
	result_7 = eliminarahamburguesa_1(&eliminarahamburguesa_1_arg, clnt);
	if (result_7 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	if (*result_7 == TRUE){
		printf("\nHaburguesa eliminada correctamente\n");
	}
	if (*result_7 == FALSE){
		printf("\nHamburguesa No Se Pudo Eliminar\n");
	}
}

void imprimirLista2(proxNodoHamburguesa parLista){
	int i=0;
	while(parLista!=NULL){
		printf("\n      Hamburguesa %i: ",i+1);
		printf("\n	Nombre de la hamburguesa: %s ",parLista->nombre);
		printf("\n	Cantidad de Ingredientes de la hamburguesa: %i \n",parLista->cantidadIngredientesExtra);
		printf("	Tipo de la hamburguesa: %s \n",parLista->tipo);
		parLista=parLista->nodoSiguiente;
		i++;
	}	
	if (i==0){
		printf("	Aun no existen hamburguesas registradas. \n");
	}
}
void imprimirLista(proxNodoHamburguesa *parLista){
	int i=0;
	while((*parLista)!=NULL){
		printf("\n      Hamburguesa %i: ",i+1);
		printf("\n	Nombre de la hamburguesa: %s ",(*parLista)->nombre);
		printf("\n	Cantidad de Ingredientes de la hamburguesa: %i \n",(*parLista)->cantidadIngredientesExtra);
		printf("	Tipo de la hamburguesa: %s \n",(*parLista)->tipo);
		(*parLista)=(*parLista)->nodoSiguiente;
		i++;
	}	
	if (i==0){
		printf("	Aun no existen hamburguesas registradas. \n");
	}
}

void listarHamburguesasCliente(CLIENT *clnt){

	proxNodoHamburguesa  *result_10;
	int  listarhamburguesassistema_1_arg;
	listarhamburguesassistema_1_arg=codigoCliente;
	printf("\n Contenido argumento listar: %i \n",listarhamburguesassistema_1_arg);
	result_10 = listarhamburguesassistema_1(&listarhamburguesassistema_1_arg, clnt);
	
	if (result_10 == (proxNodoHamburguesa *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {	
		printf("\n Mostrando listado de hamburguesas: \n");
		imprimirLista(result_10);
	}
	//printf("\n\nPresione para continuar...");
	
}

void mostrarFacturaYPago(CLIENT *clnt){

	nodo_factura  *result_8;
	int  mostrarfactura_1_arg;

	mostrarfactura_1_arg=codigoCliente;
	result_8 = mostrarfactura_1(&mostrarfactura_1_arg, clnt);
	if (result_8 == (nodo_factura *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{

		printf("-----LISTA DE HAMBRUGUESAS FACTURADAS------");
		
		imprimirLista2(result_8->listaHamburguesas);
		printf("\n INFORMACION DE FACTURA: \n");
		printf("\n	ID Factura: %s ",result_8->id_factura);
		printf("\n	Hamburguesas Pequeñas: %i",result_8->cantidadHamburguesasPequenias);
		printf("\n	Hamburguesas Medianas: %i",result_8->cantidadHamburguesasMedianas);
		printf("\n	Hamburguesas Grandes: %i",result_8->cantidadHamburguesasGrandes);
		printf("\n	Costo Sin Iva: %f",result_8->costoSinIva);
		printf("\n	Costo Iva: %f",result_8->costoIva);
		printf("\n	Costo Total: %f",result_8->costo_total);
		

		bool_t  *result_9;
		nodo_pago  pagarfactura_1_arg;

		int varOpcion;
		do{
			desplegarMenuPagos();
			scanf("%d", &varOpcion);
		
		} while (varOpcion<1 || varOpcion>5);

		if (varOpcion>0 && varOpcion<4)	{
			switch(varOpcion)
			{
				case 1: strcpy(pagarfactura_1_arg.varTipoPago,"Efectivo"); break; 
				case 2: strcpy(pagarfactura_1_arg.varTipoPago,"Targeta Credito"); break;
				case 3: strcpy(pagarfactura_1_arg.varTipoPago,"En Linea"); break;
			}
			pagarfactura_1_arg.varFactura=*result_8;
			result_9 = pagarfactura_1(&pagarfactura_1_arg, clnt);
			if (result_9 == (bool_t *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			else if (*result_9 == TRUE){
				printf("\n Pago Realizado \n");
				printf("\n GRACIAS POR SU COMPRA! Hasta pronto... \n");
				exit(EXIT_SUCCESS);
				flagSalida=1;
			}
		}
		
		
	}

}

void mostrarDatosEmpresa(CLIENT *clnt){

	nodo_datos_empresa  *result_2;
	char *consultardatosempresa_1_arg;
	nodo_costos_hamburguesa  *result_3;
	char *consultarcostoshamburguesa_1_arg;


	result_2 = consultardatosempresa_1((void*)&consultardatosempresa_1_arg, clnt);
	if (result_2 == (nodo_datos_empresa *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("\n=====DATOS EMPRESA=====");
		printf("\n	Nombre Empresa: %s",result_2->nombre);
		printf("\n	NIT: %i",result_2->nit);
	}	
	result_3 = consultarcostoshamburguesa_1((void*)&consultarcostoshamburguesa_1_arg, clnt);
	if (result_3 == (nodo_costos_hamburguesa *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("\n\n=====COSTOS HAMBURGUESAS=====");
		printf("\n PEQUENIA: %0.2f \n",(*result_3).costoHamburguesaPequenia);
		printf("\n MEDIANA: %0.2f \n",(*result_3).costoHamburguesaMediana);
		printf("\n GRANDE: %0.2f \n",(*result_3).costoHamburguesaGrande);
		printf("\n INGREDIENTES ESTRA: %0.2f \n",(*result_3).costoIngredientesExtra);
	}
	//printf("\n\nPresione tecla continuar...");
	getchar(); 
	
}

void modificarCompraHamburguesa(CLIENT *clnt){

	nodo_hamburguesa  *result_5;
	char * obtenerhamburguesa_1_arg;
	bool_t  *result_6;
	nodo_datos_hamburguesa_modificada  modificarcompra_1_arg;

	printf("\n  Ingrese Nombre Hamburguesa A Modificar: ");
	obtenerhamburguesa_1_arg=(char*)malloc(sizeof(char)*30);
	scanf("%s",obtenerhamburguesa_1_arg);
	result_5 = obtenerhamburguesa_1(&obtenerhamburguesa_1_arg, clnt);
	if (result_5 == (nodo_hamburguesa *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("\n=====Informacion Hamburguesa A Modificar:=====");
		printf("\n	Nombre de la hamburguesa: %s ",result_5->nombre);
		printf("\n	Cantidad de Ingredientes de la hamburguesa: %i \n",result_5->cantidadIngredientesExtra);
		printf("	Tipo de la hamburguesa: %s \n",result_5->tipo);

		printf("\n\n	Modificando...");
		

		nodo_hamburguesa_factura hamTemporal=crearHamburguesa();

		strcpy(modificarcompra_1_arg.nombreAntiguo,result_5->nombre);
		strcpy(modificarcompra_1_arg.varHamburguesa.nombre,hamTemporal.nombre);
		modificarcompra_1_arg.varHamburguesa.cantidadIngredientesExtra=hamTemporal.cantidadIngredientesExtra;
		strcpy(modificarcompra_1_arg.varHamburguesa.tipo,hamTemporal.tipo);
		modificarcompra_1_arg.varHamburguesa.idCliente=hamTemporal.idCliente;

		result_6 = modificarcompra_1(&modificarcompra_1_arg, clnt);
		if (result_6 == (bool_t *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else if (*result_6 == TRUE){
			printf("\n Hamburguesa Registrada Exitosamente\n");
			
		}
		else if (*result_6 == FALSE){
			printf("\n Problema al modificar factura\n");
			
		}
	
	}
	
}

void
gestion_hamburguesa_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char *getidentificador_1_arg;					

#ifndef	DEBUG
	clnt = clnt_create (host, gestion_hamburguesa, gestion_hamburguesa_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	result_1 = getidentificador_1((void*)&getidentificador_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	codigoCliente = *result_1;
	int varOpcion;

	do{
		desplegarMenu();
		scanf("%i",&varOpcion);
		switch(varOpcion){
			case 1:
				mostrarDatosEmpresa(clnt);
				break;
			case 2: 
				compraHamburguesa(clnt);			
				break;
			case 3: 
				modificarCompraHamburguesa(clnt);			
				break;
			case 4:
				eliminarHamburguesa(clnt);
				break;
			case 5:				
				listarHamburguesasCliente(clnt);
				break;
			case 6:
				mostrarFacturaYPago(clnt);
				break;
			
		}
		if (flagSalida==1){break;}

	} while(varOpcion!=0);
			

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_hamburguesa_1 (host);
exit (0);
}
