/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdlib.h>
#include <string.h>
#include "gestionHamburguesas.h"
proxNodoHamburguesa cabeza = NULL, sigHamburguesa;
proxNodoHamburguesa nuevaHamburguesa;

nodo_costos_hamburguesa * consultarcostoshamburguesa_1_svc(void *argp, struct svc_req *rqstp)
{
	static nodo_costos_hamburguesa  result;

	FILE *archivo;
	char lineaLeida[100];
	archivo = fopen("costoshamburguesa.txt","r");
	printf("\n Ejecutando Consulta de Precios. \n");
	if (archivo == NULL)
	{
		printf("Erro al abrir el archivo");
	} 		
	else
	{
			fgets(lineaLeida,100,archivo);


			result.costoHamburguesaPequenia = atof(lineaLeida);
			fgets(lineaLeida,100,archivo);
			result.costoHamburguesaMediana = atof(lineaLeida);
			fgets(lineaLeida,100,archivo);
			result.costoHamburguesaGrande = atof(lineaLeida);
			fgets(lineaLeida,100,archivo);
			result.costoIngredientesExtra = atof(lineaLeida);
	
	}
	
	
	return &result;
}

bool_t *
registrarhamburguesasistema_1_svc(nodo_hamburguesa *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	printf("\n Ejecutando Registro de Hamburguesas. \n");
	printf("	Nombre: %s \n", (*argp).nombre);
	printf("	Cantidad Ingredientes: %d \n", (*argp).cantidadIngredientesExtra);
	printf("	Tipo: %s \n", (*argp).tipo);

	nuevaHamburguesa = (proxNodoHamburguesa) malloc (sizeof (nodo_hamburguesa) );
	
	strcpy(nuevaHamburguesa->nombre,(*argp).nombre);
	nuevaHamburguesa->cantidadIngredientesExtra = (*argp).cantidadIngredientesExtra;
	strcpy(nuevaHamburguesa->tipo,(*argp).tipo);

	if (cabeza==NULL)
	{
		cabeza = nuevaHamburguesa;
		sigHamburguesa = cabeza;
	}
	else
	{
		sigHamburguesa->nodoSiguiente = nuevaHamburguesa;
		sigHamburguesa=nuevaHamburguesa;
	}
	sigHamburguesa->nodoSiguiente=NULL;
	result=TRUE;

	return &result;
}

proxNodoHamburguesa * listarhamburguesassistema_1_svc(void *argp, struct svc_req *rqstp)
{
	printf("\n Ejecutando Listar Hamburguesas. \n");
	static proxNodoHamburguesa  result;
	result = cabeza;

	return &result;
}
