/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdlib.h>
#include <string.h>
#include "gestionHamburguesas.h"
proxNodoHamburguesa cabeza = NULL, sigHamburguesa;
proxNodoHamburguesa nuevaHamburguesa;

nodo_costos_hamburguesa * consultarcostoshamburguesa_1_svc(void *argp, struct svc_req *rqstp)
{
	static nodo_costos_hamburguesa  result;

	FILE *archivo;
	char lineaLeida[100];
	char vec[4][100];
	archivo = fopen("costoshamburguesa.txt","r");

	if (archivo == NULL)
	{
		printf("Erro al abrir el archivo");
	} 		
	else
	{
		printf("\nEl contenido del archivo de prueba es \n\n");
		int i=0;
		while (feof(archivo) == 0)
		{
			fgets(lineaLeida,100,archivo);
			strcpy(vec[i],lineaLeida);
			i++;
			/*printf("%s \n",lineaLeida);*/
		}
		fclose(archivo);
	}
	result.costoHamburguesaPequenia = atof(vec[0]);
	result.costoHamburguesaMediana = atof(vec[1]);
	result.costoHamburguesaGrande = atof(vec[2]);
	result.costoIngredientesExtra = atof(vec[3]);
	return &result;
}

bool_t *
registrarhamburguesasistema_1_svc(nodo_hamburguesa *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	printf("Nombre: %s \n", (*argp).nombre);
	printf("Cantidad Ingredientes: %s \n", (*argp).cantidadIngredientesExtra);
	printf("Tipo: %s \n", (*argp).tipo);

	hamburguesaHamburguesa = (proxNodoHamburguesa) malloc (sizeof (nodo_hamburguesa) );
	
	strcpy(nuevaHamburguesa->nombre,(*argp).nombre);
	if (cabeza==NULL)
	{
		cabeza = nuevaHamburguesa;
		sigHamburguesa = cabeza;
	}
	else
	{
		sigHamburguesa->nodoSiguiente = nuevaHamburguesa;
		sigHamburguesa=nuevaHamburguesa;
	}
	sigHamburguesa->nodoSiguiente=NULL;
	result=TRUE;

	return &result;
}

proxNodoHamburguesa * listarhamburguesassistema_1_svc(void *argp, struct svc_req *rqstp)
{
	static proxNodoHamburguesa  result;
	result = cabeza;

	return &result;
}
