/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionHamburguesas.h"

nodo_costos_hamburguesa *
consultarcostoshamburguesa_1_svc(void *argp, struct svc_req *rqstp)
{
	static nodo_costos_hamburguesa  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
registrarhamburguesasistema_1_svc(nodo_hamburguesa *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

proxNodoHamburguesa *
listarhamburguesassistema_1_svc(void *argp, struct svc_req *rqstp)
{
	static proxNodoHamburguesa  result;

	/*
	 * insert server code here
	 */

	return &result;
}
