/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdio.h>
#include <stdlib.h>
#include "gestionFacturas.h"

int *
consultarnumfacturas_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	FILE *archivo;

	char lineaLeida[100];
	int contador=0;
	archivo = fopen("../ServidorControlPedidos/Facturas/PagosFacturas.txt","r");

	if (archivo == NULL)
	{
		printf("Erro al abrir el archivo");
	} 		
	else
	{
		printf("\nContando pagos de facturas (total facturas)... \n\n");
		while (feof(archivo) == 0)
		{
			fgets(lineaLeida,100,archivo);
			contador++;
		}
		fclose(archivo);
	}
	result=contador-1;
	return &result;
}

float *
consultarcostototalcompras_1_svc(void *argp, struct svc_req *rqstp)
{
	static float  result;

	FILE *archivo;

	char lineaLeida[100];
	float sumatoria=0.0;
	float valLeido;

	archivo = fopen("../ServidorControlPedidos/Facturas/PagosFacturas.txt","r");

	if (archivo == NULL)
	{
		printf("Erro al abrir el archivo");
	} 		
	else
	{
		printf("\nObteniendo costo total... \n\n");
		while (feof(archivo) == 0)
		{
			fgets(lineaLeida,100,archivo);
			valLeido = atof(lineaLeida);
			printf("\n El valor leido es:%f\n",valLeido);
			sumatoria=sumatoria+valLeido;

		}
		fclose(archivo);
	}

	result = sumatoria-valLeido;

	return &result;
}
